config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'pages#home'
  get '/creative', to: 'pages#creative'
  get '/location', to: 'pages#location'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  CREATIVEEXCUSES = [
    { id: 1, excuse: 'the dog ate my homework!', gif: 'https://media.giphy.com/media/3oEduXKKfBX6PPLiGQ/giphy.gif'},
    {id: 2, excuse: 'I was probed by aliens', gif: 'https://media.giphy.com/media/ZO3sm9HfmdolO/giphy.gif'},
    {id: 3, excuse: 'I got food poisoning last night', gif: 'https://media.giphy.com/media/127n1Og9Zmw83C/giphy.gif'}
  ]
  def home
  end

  def creative
    @excuse = CREATIVEEXCUSES.sample
  end

  def location
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExcuseGen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/creative.html.erb
<div class="container">
   <div class="location-form">
    <h2>Creative Excuse #<%= @excuse[:id] %></h1>
    <img src=<%= @excuse[:gif] %> alt="">
    <p><%= @excuse[:excuse] %></p>
     <div class="d-flex">
      <%= link_to "👍🏼", location_path, {class: 'cta-btn'} %>
      <%= link_to "👎🏼", creative_path, {class: 'other-btn'} %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="homepage">
    <h1>Excuse Engine</h1>
    <div class="d-flex flex-column">
      <%= link_to "Location Excuse", location_path, {class: 'cta-btn'} %>
      <%= link_to "Creative Excuse", creative_path, {class: 'other-btn'} %>
    </div>
  </div>
</div>

app/views/pages/location.html.erb
<div class="container">
   <div class="location-form">
    <h2>Take the excuse engine 🚂 to where you are going!</h1>
    <form action="/excuse/:id" method="get">
      <div class="form-group">
        <label for="coming-from" class="sr-only">Coming from:</label>
        <input type="text" name="coming-address" placeholder="start point">
      </div>
       <div class="form-group">
        <label for="coming-from" class="sr-only">Going to:</label>
        <input type="text" name="going-address" placeholder="end point">
      </div>
      <button type="submit" class="cta-btn">Excuse Me!</button>
    </form>
  </div>
</div>